export const labelMap = {
  id: null,
  patient_id: null,
  patient_id_id: null,
  name: "Name",
  role: "Role",
  email: "Email",
  count: "Total",
  created_at: "Created Date",
  total_phage_patients: "Total Phage Patients",
  phagestate: "Phage Status",
  phage_analysis_start_date: "Analysis Start Date",
  phage_administered: "Administered",
  phage_dose: "Dose (ml)",
  treatment_duration_days: "Treatment Duration (Days)",
  clinical_outcome: "Clinical Outcome",
  time_to_clearance_days: "Clearance Time (Days)",
  mortality_30day: "30-Day Mortality",
  collection_date: "Collection Date",
  is_submit_phage: "Submitted for Phage",
  updated_at: "Updated At",
};
